language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: F5cOUGOhB0TRircgpwlDqPG0jG2WWfAsh+NdVBKxO6aDauKQ4bVI1AER/+Qm65wLUx1zRxksdY33/j6wtnvqSOIbvei4ryo2VNF5mvsiZfByE5AqZLG9R2MjvI4udb6Zdy5Oh9vN4lWtFq0Ey0fQurufyIEDV9ajwiCXAlV1C5mZaai4gLG5HkPhKy+HgwDfJAcyzIJEcThwx3ohRUT/vXnUvnAx9Phclia+IiPqKTGB2xQUbXBsaSACndmBzs/uzTsu9drjCA/pXqhvWJ7JEKs132MG6kS+16Gyz0gG9ozD9GMZBkkrSADhVmof8p2fEMiO/+BTA9LVTJFuj+fJmP5oriCmMSN2R+ChbIofVj1r2JtCttc4sxt3squ/+OiERXKRPkXxYODu+W+zsaGX+ay4ogrlFpRCyPgy8i9WU80PUTEJiSzeNHIGHypNbw0KMLsn7/pP2mWK88Tui7ad1XR3Mc9KN2WjvwOnEo4v5mvJochDL5wzfGz8lZLNxg9ZgNrAWntvnukpGbhkyw3/QDsrc0Tvl08QGTHHmMM20w+05MCegTlk48eB/Kt2t/gJLGgTwT/sV4FG9TF7yQ67KRKm7mECDTD++Q6XtZKXv+FVTl7RkH0DDAtGz6DAvu4FI2mLus/m5khGehDPa4KEHcIP9ZscN8UA2oSItlPnD/E=
  app: salty-plains-53230
  on:
    repo: llamousse/caffeinated
